###################################################################################################
###  WARNING: This is a generated file, do not edit this file as changes will                   ###
###           be overwritten when the BAF (Buildsystem Agnostic File) is                        ###
###           parsed anew.                                                                      ###
###                                                                                             ###
###           To regenerate this file manually, please refer to the BAF README:                 ###
###           https://gitlabinternal.softathome.com/sofa/gitlab-ci/baf/-/blob/master/README.md  ###
###################################################################################################
-include $(STAGINGDIR)/sahcommon.mk

export INSTALL ?= install
export STRIP ?= strip

export PKG_CONFIG_LIBDIR ?= $(STAGINGDIR)/build/pkg-config
export BINDIR ?= /usr/bin
export LIBDIR ?= /usr/lib
export SLIBDIR ?= /slib
export LUALIBDIR ?= /usr/lib/lua
export INCLUDEDIR ?= /include
export INITDIR ?= /etc/init.d
export ACLDIR ?= /etc/acl
export DOCDIR ?= $(STAGINGDIR)/doc/memtrace
export PROCMONDIR ?= /usr/lib/processmonitor/scripts
export RESETDIR ?= /etc/reset
export MACHINE ?= $(shell $(CC) -dumpmachine)

export COMPONENT = memtrace
export O = ../output/$(MACHINE)

all:
	$(MAKE) -C memtrace all

clean:
	$(MAKE) -C memtrace clean

install:
	$(INSTALL) -D -p -m 0755 output/$(MACHINE)/libmemtrace-agent.so $(STAGINGDIR)/usr/lib/libmemtrace-agent.so
	$(INSTALL) -D -p -m 0755 output/$(MACHINE)/$(COMPONENT) $(STAGINGDIR)$(BINDIR)/$(COMPONENT)
	$(INSTALL) -D -p -m 0755 memtrace/scripts/memtrace-endurance $(STAGINGDIR)$(BINDIR)/memtrace-endurance

release:
	$(call install_so_release,libmemtrace-agent.so,/usr/lib)
	$(INSTALL) -D -p -m 0755 $(STAGINGDIR)$(BINDIR)/$(COMPONENT) $(ROOT_FS_DIR)$(BINDIR)/$(COMPONENT)
	$(STRIP) $(ROOT_FS_DIR)$(BINDIR)/$(COMPONENT)
	$(INSTALL) -D -p -m 0755 $(STAGINGDIR)$(BINDIR)/memtrace-endurance $(ROOT_FS_DIR)$(BINDIR)/memtrace-endurance

build_package:
	$(MAKE) -f Component.mk release ROOT_FS_DIR=$(COMP_PACKAGE_DIR)

release_package:
	cp -af $(COMP_PACKAGE_DIR)/* $(ROOT_FS_DIR)

.PHONY: all clean install release build_package release_package