# BEGIN-INTERNAL
###################################################################################################
###  WARNING: This is a generated file, do not edit this file as changes will                   ###
###           be overwritten when the BAF (Buildsystem Agnostic File) is                        ###
###           parsed anew.                                                                      ###
###                                                                                             ###
###           To regenerate this file manually, please refer to the BAF README:                 ###
###           https://gitlabinternal.softathome.com/sofa/gitlab-ci/baf/-/blob/master/README.md  ###
###################################################################################################
# END-INTERNAL
-include $(CONFIGDIR)/components.config

export INSTALL ?= install
export PKG_CONFIG_LIBDIR ?= /usr/lib/pkgconfig
export BINDIR ?= /usr/bin
export LIBDIR ?= /usr/lib
export SLIBDIR ?= /usr/lib
export LUALIBDIR ?= /usr/lib/lua
export INCLUDEDIR ?= /usr/include
export INITDIR ?= /etc/init.d
export ACLDIR ?= /etc/acl
export DOCDIR ?= $(D)/usr/share/doc/memtrace
export PROCMONDIR ?= /usr/lib/processmonitor/scripts
export RESETDIR ?= /etc/reset
export MACHINE ?= $(shell $(CC) -dumpmachine)

export COMPONENT = memtrace
export O = ../output/$(MACHINE)

compile:
	$(MAKE) -C memtrace all

clean:
	$(MAKE) -C memtrace clean

install:
	$(INSTALL) -D -p -m 0755 output/$(MACHINE)/libmemtrace-agent.so $(D)/usr/lib/libmemtrace-agent.so
	$(INSTALL) -D -p -m 0755 output/$(MACHINE)/$(COMPONENT) $(D)$(BINDIR)/$(COMPONENT)
	$(INSTALL) -D -p -m 0755 memtrace/scripts/memtrace-endurance $(D)$(BINDIR)/memtrace-endurance

.PHONY: compile clean install
